Basic code for sponskrub integration
blackjack4494/yt-dlc pull request #212
Opened 2020-11-15 00:36 UTC by pukkandan

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Use SponSkrub to cut out sponsor segments from youtube videos. Closes #209 

This is currently just a proof of concept. It needs more testing and refinement before being ready for use.

2020-11-15 07:23 UTC, shakeyourbunny commented
Note that there is no binary for windows there.

2020-11-15 19:27 UTC, pukkandan commented
I need some help with a few things:
1. What should be the default. Currently it is off by default, but it can be set to on if the executable exists.
2. What should be the default arguments? Maybe `-chapter`? That will ensure it is fast and non-destructive.
3. SponsKrub is pointless for non-youtube videos. But I can't seem to find `ie_key` in the `information` object. Is there another way to quickly and  reliably tell if it is a youtube video?

4. If the download is run multiple times, the post-processors are re-run each time. When sponskrub is used without `-chapter`, this causes the video to get cut up again and again at the sponsor timestamps. This is a major issue. I have no idea how to fix this. Anybody has any ideas?

2020-11-15 19:53 UTC, pukkandan commented
Also, I am testing the code only in x64 windows Cpython 3.8.4
I'd appreciate it if someone can test it in other systems.

2020-11-16 15:24 UTC, ajayyy requested changes

2020-11-16 15:24 UTC, ajayyy commented on youtube_dlc/postprocessor/sponskrub.py
> +            self._downloader.to_screen('[sponskrub] No data in database')
```suggestion
            self._downloader.to_screen('[sponskrub] No segments in the SponsorBlock database')
```

2020-11-16 15:24 UTC, ajayyy commented on youtube_dlc/options.py
> +    extractor = optparse.OptionGroup(parser, 'SponSkrub Options')
```suggestion
    extractor = optparse.OptionGroup(parser, 'SponSkrub Options (SponsorBlock)')
```

2020-11-17 13:57 UTC, pukkandan commented
> If the download is run multiple times, the post-processors are re-run each time. When sponskrub is used without -chapter, this causes the video to get cut up again and again at the sponsor timestamps. This is a major issue. I have no idea how to fix this. Anybody has any ideas?

I can't complete the feature without some help in this matter.

2020-11-17 15:09 UTC, JanPokorny commented
@pukkandan One possible solution: modify SponSkrub (add a config flag) so it checks the video length and no-ops if it doesn't match. Would that work?

2020-11-17 17:55 UTC, pukkandan commented
@JanPokorny It is a good idea. However, I don't know any DLang (in which SponsKrub is written). Let me see if this can be implemented in the PostProcessor itself.

2020-11-17 18:01 UTC, JanPokorny commented
Maybe @faissaloo wants to implement this feature for SponSkrub? IDK if the SponsorBlock API returns the video length, but if it does, that should be an easy enough change. I could see this being useful outside of this issue, since checking the video length before cutting it up seems like a reasonably general sanity check.

2020-11-17 18:13 UTC, faissaloo commented
>     4\. If the download is run multiple times, the post-processors are re-run each time. When sponskrub is used without `-chapter`, this causes the video to get cut up again and again at the sponsor timestamps. This is a major issue. I have no idea how to fix this. Anybody has any ideas?

Trying to understand the context here, what would be a likely reason for running the download multiple times? I assume a download is done to completion right?

2020-11-17 18:28 UTC, pukkandan commented
@faissaloo If a playlist download is run multiple times without using archive, for example.
youtube-dlc will see that the video file already exists and won't download it again. But the postprocessors WILL be run again

2020-11-17 18:31 UTC, JanPokorny commented
@pukkandan That seems like a weird behavior tbh, I would expect that filters aren't supposed to be idempotent. Maybe @blackjack4494 can tell us more on how it works?

2020-11-17 18:48 UTC, faissaloo commented
@pukkandan 
>  youtube-dlc will see that the video file already exists and won't download it again. But the postprocessors WILL be run again

I have to agree with @JanPokorny, this seems like an issue with youtube-dlc. I wouldn't expect such a thing to be in the purview of the application doing the processing, rather the application managing the download should determine for itself whether or not it has downloaded something.

2020-11-17 20:53 UTC, pukkandan commented
@JanPokorny @faissaloo I have implemented a solution for this by ensuring that the postprocessor is run only if the video was downloaded/merged in the current run. A solution based on file duration is superior imo, but I'll leave that for someone else to implement.

I am also turning it on by default if sponskrub binary can be found. That is how mergerPP works, so it makes sense to do the same here.

2020-11-26 17:26 UTC, shivasagarrao commented
@pukkandan Small request is try to implement this feature in [youtube-dl](https://github.com/ytdl-org/youtube-dl)  as well.

2020-11-26 17:50 UTC, pukkandan commented
@shivasagarrao This patch can be used in youtube-dl without any changes. But I honestly am not interested in making any PRs over there. Feel free to cherry-pick my commits and make a PR over there yourself

2021-01-22 00:51 UTC, closed without merging