Merging the latest version of youtube-dl
blackjack4494/yt-dlc pull request #245
Opened 2020-11-20 00:13 UTC by pukkandan

This is my attempt at merging 'ytdl-org/youtube-dl/master' release 2020.11.19 into youtube-dlc

I have tried to resolve all conflicts by preferring youtube-dl's code when it doesn't sacrifice any functionality of dlc
Major changes needed to be made only to youtube and vlive extractor.

For vlive, youtube-dl no longer has a `playlist` extractor. I do not know why this is. So I have kept the playlist extractor from dlc while replacing the others.

For youtube,  `Channel` and `Playlists` extractors have been replaced by the new `Tab` extractor. 

youtube-dl no longer has YoutubeSearchURLIE , YoutubeFavouritesIE or YoutubeShowIE extractors.
* I rewrote the searchURL extractor to piggyback on search extractor
* Wrote favourites extractor to download liked videos since youtube.com/my_favorites no longer exists
* I am not sure whether youtube still has show URLs. I couldn't find any. So I removed it.
* I also simplified the WatchLater extractor. Now watchlater and favourites can be accessed by their direct IDs `WL` and `LL` respectively in addition to `:ytwatchlater`, `:ytfav`
* I have kept the age gate fix in the main extractor intact. However, it would be wise to rigorously review that section of the code again

2020-11-20 00:32 UTC, pukkandan commented
Consider this a work in progress. I really need to get some sleep right now. I will look at any failing tests tomorrow.

I would really appreciate it if someone can test/review this

2020-11-20 07:39 UTC, pukkandan commented
@kyuyeunk I see that you have some PRs open regarding vlive. So I assume you are familiar with its code. Can you have a look at youtube-dl's vlive extractor code and check how much of it we can/should merge

2020-11-20 10:10 UTC, pukkandan commented
Another thing that is worth noting before merging this is that the youtube extractor behaves differently now. Now it directly downloads the videos in the URL that is given to it instead of trying to interpret it as user/channel/playlist etc. 

For example, in older versions, if you tried to download `https://www.youtube.com/user/HBO`, you would get all the uploads by HBO. But now, it downloads the playlists in the home page ("Transhood TRANSlation Summit" and "New on HBO
"). If you want to download the whole channel, you must give the URL `https://www.youtube.com/user/HBO/videos`

I am not sure how to revert this to older behaviour or if it even should be reverted in the first place

2020-11-20 13:29 UTC, pukkandan commented
Making youtube direct URLs work without any false positives was much harder than I thought. 

For example, `/AsapSCIENCE` and `/feed` are valid, but `/embed`, `/feed/library` are not.

I ended up having to keep a record of the reserved names and perform a negative lookahead. If anyone has a better idea to fix this, you are welcome to try.

    _RESERVED_NAMES = (
        r'course|embed|watch|w|results|storefront|'
        r'shared|index|account|reporthistory|t/terms|about|upload|signin|logout|'
        r'feed/(watch_later|history|subscriptions|library|trending|recommended)')

2020-11-20 13:30 UTC, pukkandan commented
@blackjack4494 Please review and merge this when you have time

2020-11-20 14:34 UTC, SeonjaeHyeon commented
I think we don't need to merge vlive extractor codes from youtube-dl. The plugin was already fixed #101 .
And @kyuyeunk opened PR for playlist support #223 .

2020-11-20 15:07 UTC, kyuyeunk commented
> @kyuyeunk I see that you have some PRs open regarding vlive. So I assume you are familiar with its code. Can you have a look at youtube-dl's vlive extractor code and check how much of it we can/should merge

I've compared the `vlive.py` for youtube_dl and youtube_dlc and came to following conclussions.

1. **youtube_dl does not support new url format while youtube_dlc does.**
`vlive.tv` recently started supporting two types (i.e., old and new) urls. Which are `https://www.vlive.tv/video/<videoId>` and `https://www.vlive.tv/post/<postId>`.
For example, https://www.vlive.tv/video/111110 (old) and https://www.vlive.tv/post/1-18363798 (new) both points to the same video.
While youtube_dl only supports old url types, youtube_dlc supports both old and new types.

2. **youtube_dl uses web api to fetch data that is only needed while youtube_dlc downloads whole web page and parse the data.**
I personally think approach of youtube_dl feels more proper. But web api that is being used only supports `videoId` and not `postId`.

3. **youtube_dl gathers more data about a video.**
youtube_dl versions gather information such as views, durations. Which will come in handy if a user uses options such as `--min-views`, or `--get-duration`.

All in all, `vlive.py` in youtube_dlc is superior because of number 1 - it works for both old and new type of urls. So there is no urgent need to change/merge it with youtube_dl version.

Meanwhile, I will try to work on a code that is based on youtube_dl version that also supports new url type and make a pull request of it. This is mostly because of reasons stated in 2 and 3. Also, maintaining similarity between youtube_dl and youtube_dlc codebase could be important.

2020-11-20 15:13 UTC, pukkandan commented
@kyuyeunk I agree with you. While maintaining code similarity to youtube-dl is important, there is no need for us to do so at the cost of functionality. I will leave `vlive.py` completely out of the merge. Meanwhile you can work on it at your own pace

2020-11-21 21:40 UTC, pukkandan commented
I have added support for ytsubs, ythistory, ytrec. So all youtube extractors should be working correctly now. I have set maximum page count to 5 for the timebeing.

2020-11-22 18:47 UTC, Zirro commented
> Another thing that is worth noting before merging this is that the youtube extractor behaves differently now. Now it directly downloads the videos in the URL that is given to it instead of trying to interpret it as user/channel/playlist etc.
> 
> For example, in older versions, if you tried to download `https://www.youtube.com/user/HBO`, you would get all the uploads by HBO. But now, it downloads the playlists in the home page ("Transhood TRANSlation Summit" and "New on HBO"). If you want to download the whole channel, you must give the URL `https://www.youtube.com/user/HBO/videos`
> 

Sudden changes in behaviour here could be problematic for those of us who regularly crawl a large number of channels in the background, causing a lot of unwanted content from other channels to get downloaded instead. I think the change by itself might make sense - especially if it remains consistent with youtube-dl's behaviour going forward - but if you could print a deprecation warning for a few releases when an affected URL is provided before the change is made I'm sure it'll save quite a few headaches for all the archivers out there.

2020-11-22 19:10 UTC, pukkandan commented
@Zirro It is a change introduced by youtube-dl itself. I also prefer it the old way. It is easy enough to "fix" it by redirecting the channel home page to `/video`. 

But in that case, there would be no way for the user to download the home page (why someone would want to do that, I dont know). Also, this will make dlc behave differently than dl, which in my opinion is not a good idea.

Adding a warning is a good idea. I don't know how much actual practical value it has, but there is no harm in adding it.

2020-11-22 20:01 UTC, Zirro commented
> I also prefer it the old way.

I think you may have misunderstood me - I'm fine with either behaviour as the default in the long run. My hesitation is about changing it right away without a prior warning/notice to users.

If a temporary condition is added to retain the old behaviour (by appending `/videos` to bare channel/user URLs for instance) which also causes a warning to be printed over the next month or so, that is hopefully enough time for people to notice it and update their commands and scripts to include `/videos` everywhere they want the previous behaviour.

2020-11-22 20:31 UTC, pukkandan commented
@Zirro I have added a commit that redirects channel homepage to /video and issues a warning about the redirect. The warning currently does not mention any future plans. It can easily be added if we decide that the redirection to /videos will be temporary.

@blackjack4494 I would like to know your opinion on this matter

2020-11-22 20:58 UTC, makeworld-the-better-one commented
As the creator of #237 I disagree this PR closes the issue. I was wondering about a general policy/strategy around upstream updates, not for an update to happen. Please remove it from your original PR comment so it won't be closed automatically.

2020-11-22 21:43 UTC, pukkandan commented
@makeworld-the-better-one You just added that title :/

Previously, the issue was only asking when the current releases will be updated
> Several new youtube-dl versions have been released since it was taken down (and now reinstated). When and how do those updates get merged here?

Anyway, I have removed the reference

2020-11-22 21:44 UTC, makeworld-the-better-one commented
Sorry, I thought it was more clear from the beginning. Thanks for changing your comment.

2020-11-23 01:20 UTC, blackjack4494 reviewed
reviewed roughly half already.

2020-11-23 02:44 UTC, survirtual commented
Be advised, I tested this pull request and it does not fix issue #172 in the case of playlist?list=LM on YouTube, as follows:
https://www.youtube.com/playlist?list=LM

Only the first 100 videos are detected and downloaded.  On that issue, it shows this PR as closing it.

2020-11-23 05:28 UTC, pukkandan commented
@survirtual You are right. I am sure it was working when I tested it though. But now no playlist can see more than one page. I will look into it asap

2020-11-23 06:45 UTC, pukkandan commented
@survirtual The issue was reintriduced by https://github.com/ytdl-org/youtube-dl/commit/e2096776b99e4b5b67aacd1bcc7807a3d3757236#diff-0f24619cf9483f3bea670bba396939af35ea780edba90bb9d96ab20aae43386fR2998

I have made a patch. I tested it using `WL` and `LL`. My `LM` is too small to test. Please let me know if this solved the issue.

2020-11-23 07:56 UTC, pukkandan commented
@blackjack4494 Awesome. But I @ you to ask what your opinion is on this matter.

> > Another thing that is worth noting before merging this is that the youtube extractor behaves differently now. Now it directly downloads the videos in the URL that is given to it instead of trying to interpret it as user/channel/playlist etc.
> > For example, in older versions, if you tried to download `https://www.youtube.com/user/HBO`, you would get all the uploads by HBO. But now, it downloads the playlists in the home page ("Transhood TRANSlation Summit" and "New on HBO"). If you want to download the whole channel, you must give the URL `https://www.youtube.com/user/HBO/videos`
> 
> Sudden changes in behaviour here could be problematic for those of us who regularly crawl a large number of channels in the background, causing a lot of unwanted content from other channels to get downloaded instead. I think the change by itself might make sense - especially if it remains consistent with youtube-dl's behaviour going forward - but if you could print a deprecation warning for a few releases when an affected URL is provided before the change is made I'm sure it'll save quite a few headaches for all the archivers out there.


Also, just out of curiosity, are you the only maintainer for this repo?

2020-11-23 15:21 UTC, survirtual commented
@pukkandan commit [b973982](https://github.com/blackjack4494/yt-dlc/pull/245/commits/b9739824a509e17010171ab52a23ec8db72fac2f) confirmed to fix the issue.  Nice work, thank you!

Will you be creating a PR with your fix on youtube-dl?  I opened an issue on the repo here: [ytdl-org/youtube-dl/issues/27157](https://github.com/ytdl-org/youtube-dl/issues/27157)

2020-11-23 17:07 UTC, pukkandan commented
@survirtual no, all that is needed to fix the issue in yt-dl is to revert this line 
https://github.com/ytdl-org/youtube-dl/commit/e2096776b99e4b5b67aacd1bcc7807a3d3757236#diff-0f24619cf9483f3bea670bba396939af35ea780edba90bb9d96ab20aae43386fR2998

I am not going to make a PR for it. Feel free to do it if you want, though

2020-11-23 22:27 UTC, pukkandan commented
@nixxo youtube-dl now has a skyit extractor. Could you please have a look at it and see if it can completely replace your skyitalia extractor?

2020-11-26 16:39 UTC, Zirro commented
The previously mentioned change in how bare channel/user URLs are handled has indeed caused problems for some users of youtube-dl: https://github.com/ytdl-org/youtube-dl/issues/27186 / https://old.reddit.com/r/DataHoarder/comments/k114wq/youtubedl_will_now_download_all_linked_channels/

In the end, I think the old behaviour is more intuitive and what both new and old users would expect these URLs to result in. The idea of someone wanting to specifically save only the videos and playlists visible on a user's home page seems so rare that I'm inclined to say that the old behaviour should be kept (redirecting to /videos, unless /home is explicity provided) and that no message informing people about `/home` is required. Perhaps it could be documented somewhere here in the repository, though.

2020-11-26 16:59 UTC, pukkandan commented
@Zirro I agree. Which is why I have already reversed the change. I do however think that the warning must be kept since it a  behaviour that is different from the main yt-dl repository.

2020-11-26 17:51 UTC, Zirro commented
Okay, sounds good to me. While testing this PR I found another issue that resulted in unexpected videos being downloaded, though it is more of an edge case. I had a few incorrect entries along the line of [https://www.youtube.com/watch?list=UUXIkr0SRTnZO4_QpZozvCCA](https://www.youtube.com/watch?list=UUXIkr0SRTnZO4_QpZozvCCA) (where `/watch` should be `/playlist`) in my list of URLs to download. I hadn't noticed before, as the previous code appeared to handle these as playlists either way (arguably the appropriate approach is to throw an error).

However, unlike most incorrect paths on the site which result in either a 404 or a YouTube-specific error, `/watch` with unknown parameters apparently redirects to YouTube's front page and causes `yt-dlc` to start downloading the videos there. This should probably be caught as an invalid URL/error at an earlier stage.

2020-11-26 19:15 UTC, pukkandan commented
>  I had a few incorrect entries along the line of https://www.youtube.com/watch?list=UUXIkr0SRTnZO4_QpZozvCCA (where /watch should be /playlist) in my list of URLs to download

@Zirro Generally speaking, users shouldn't expect youtube-dl to handle redirects caused by invalid URLs correctly. But for this specific case, I have made a patch. It will issue a warning and then download the playlist.

2020-11-30 00:54 UTC, blackjack4494 reviewed
50/66
had some troubles with few extractors. sometimes vpn did the job. guess most of the time it's my connection dropping.

2020-11-30 00:59 UTC, blackjack4494 commented
> @Zirro I have added a commit that redirects channel homepage to /video and issues a warning about the redirect. The warning currently does not mention any future plans. It can easily be added if we decide that the redirection to /videos will be temporary.
> 
> @blackjack4494 I would like to know your opinion on this matter

Yeah changing current behaviour out of the blue may raise issues. It's better to do some light transitioning over time.



> @blackjack4494 Awesome. But I @ you to ask what your opinion is on this matter.
> 
> > > Another thing that is worth noting before merging this is that the youtube extractor behaves differently now. Now it directly downloads the videos in the URL that is given to it instead of trying to interpret it as user/channel/playlist etc.
> > > For example, in older versions, if you tried to download `https://www.youtube.com/user/HBO`, you would get all the uploads by HBO. But now, it downloads the playlists in the home page ("Transhood TRANSlation Summit" and "New on HBO"). If you want to download the whole channel, you must give the URL `https://www.youtube.com/user/HBO/videos`
> > 
> > 
> > Sudden changes in behaviour here could be problematic for those of us who regularly crawl a large number of channels in the background, causing a lot of unwanted content from other channels to get downloaded instead. I think the change by itself might make sense - especially if it remains consistent with youtube-dl's behaviour going forward - but if you could print a deprecation warning for a few releases when an affected URL is provided before the change is made I'm sure it'll save quite a few headaches for all the archivers out there.
> 
> Also, just out of curiosity, are you the only maintainer for this repo?

right now i am the only maintainer. have already asked if some other people were interested. there were two people I had in mind a way back then. Will try to add 1-2 maintainer the following week if they are interested.

Really tried to release an updated version this weekend but didn't make it due to be being more busy than I expected.

2020-11-30 01:11 UTC, blackjack4494 requested changes
something is broken in viki extractor. related to subtitles. I guess some header is missing.

2020-11-30 01:15 UTC, blackjack4494 approved these changes
Even though I approve this now there are some (minor) issues with  
googledrive  
youtube  
viki  
vlive  

but those can be fixed afterwards.

2020-11-30 01:20 UTC, merged

2020-11-30 02:24 UTC, blackjack4494 commented
As for youtube downloading behaviour:
yt-dlc should download channles like it is expected as usual.  
however there will be some light transition. 

What I thought of is a flag that will change to new/experimental downloading like youtube-dl behaves now. Later on this behaviour could become standard but it should be possible to switch back to old behaviour with another flag.  
This is the most friendly way I can think of. Allowing depending scripts/programs to adapt to new changes by experimenting with new changes but maintaining the old behaviour in the meantime. Then at some point they could still use the old behaviour with a new flag. 

@pukkandan tell me what you think. haven't digged deep into how you reverted to old behaviour. maybe it's as simple as to check a certain parameter to change behaviour.

2020-11-30 06:22 UTC, pukkandan commented
> Even though I approve this now there are some (minor) issues with
> googledrive
> youtube
> viki
> vlive
> 
> but those can be fixed afterwards.

Could you elaborate on what the exact issues are? Then I could have a look

> @pukkandan tell me what you think. haven't digged deep into how you reverted to old behaviour. maybe it's as simple as to check a certain parameter to change behaviour.

I look at the provided URL and if it directly points to the channel page, append a `/video` to it (https://github.com/blackjack4494/yt-dlc/pull/245/commits/036fcf3aa1fbd484c6629ab754eae715d21439a5). Adding a switch to reverse it would be easy.

2020-11-30 17:51 UTC, pukkandan commented
@blackjack4494 I found a minor bug in the code and have pushed a commit to fix it. Should I make it a separate PR?

2020-11-30 18:53 UTC, nixxo commented
> 
> 
> @nixxo youtube-dl now has a skyit extractor. Could you please have a look at it and see if it can completely replace your skyitalia extractor?

I looked at it and yes, you can replace my skyitalia extractor with skyit. It supports more websites.

2020-11-30 19:25 UTC, pukkandan commented
@nixxo This PR has already been merged. Could you make a seperate PR with just the skyitalia extractor

2020-12-01 11:34 UTC, nixxo commented
@pukkandan pr done. #270